- job:
    name: 'installer-build'
    node: 'traf_bld'

    builders:
      - link-logs
      - multi-git-prep:
           repos: "trafodion/install"
      - pkg-install

    publishers:
      - console-log

- job:
    name: 'installer-pub'
    node: 'traf_bld'

    builders:
      - link-logs
      - clean-workspace
      - multi-git-prep:
           repos: "trafodion/install"
      - pkg-install
      - stage-install

    publishers:
      - console-log
      - traf-upload-to-cdn
      - traf-release-tar

# Simple file type check can run on master
# Does not need to be exclusive
- job-template:
    name: 'gate-{name}-check-for-binary'
    node: master

    builders:
      - link-logs
      - gerrit-git-prep
      - assert-no-binary-files
      - assert-no-bad-source-files

    publishers:
      - console-log

# Product builds of each flavor
- job-group:
    name: 'build-product'
    flavor:
      - "release"
      - "debug"

    jobs:
      - build-product-{flavor}

# Build procedure for trafodion
# Publish jenkins artifacts to be used by downstream test jobs
# Include build-check tests
- job-template:
    name: 'build-product-{flavor}'
    node: 'traf_bld'

    builders:
      - link-logs
      - clean-buildspace
      - multi-git-prep:
           repos: "trafodion/core trafodion/install trafodion/dcs"
      - pkg-traf:
           flavor: "{flavor}"
      - check-build:
           dir: "trafodion/core"
      - pkg-dcs:
           buildDir: "trafodion/dcs"
           coreJDBC: "trafodion/core"
      - check-build:
           dir: "trafodion/dcs"
      - pkg-install
#      no .gitignore in install
#      - check-build:
#           dir: "trafodion/install"
      - stage-traf:
           flavor: "{flavor}"

    publishers:
      - traf-upload-to-cdn
      - traf-release-tar
      - archive:
          artifacts: 'trafodion/install/install*.tar.gz'
      - archive:
          artifacts: 'trafodion/dcs/target/dcs*.tar.gz'
      - archive:
          artifacts: 'trafodion/core/trafodion-regress.tgz'
      - archive:
          artifacts: 'trafodion/core/trafodion_clients*.tgz'
      - archive:
          artifacts: 'trafodion/core/trafodion_server*.tgz'
      - archive:
          artifacts: 'trafodion/core/rest/target/rest*.tar.gz'
      - console-log
      - git-log
      - traf-make-log
