# To-Do: add Check-Full-PR job to be triggered only on phrase

- job:
    name: 'Check-PR'
    node: 'master'
    project-type: multijob

    parameters:
      - string:
          name: LOG_PATH
          default: 'PullReq/$ghprbPullId/$BUILD_NUMBER'

    properties:
      - github:
          url: https://github.com/apache/incubator-trafodion

    scm:
      - git:
          url: https://github.com/apache/incubator-trafodion
          wipe-workspace: false
          skip-tag: true
          refspec: '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*'
          branches: 
            - 'origin/pr/${ghprbPullId}/head'
          changelog-against:
            remote: origin
            branch: '${ghprbTargetBranch}'

    triggers:
      - github-pull-request:
          # check for new PR every few minutes
          cron: H/6 * * * *
          # github user names for test approval
          admin-list:
            - svarnau
            - alchen99
          white-list:
            - nonstop-qfchen
            - selvaganesang
            - xwq
            - HowardQin
            - anoopsharma00
            - hegdean
          allow-whitelist-orgs-as-admins: true
          org-list:
            - trafodion-contributors

    builders:
      - link-logs
      - shell: sudo -n -E /usr/local/bin/cancel-prior-PR.sh
      - multijob:
          name: static
          projects:
            - name: "static-checks"
              current-parameters: true
              predefined-parameters: |
                 LOG_PATH=$LOG_PATH/static-checks
      - multijob:
          name: build_test
          projects:
            - name: "build-debug"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=$LOG_PATH/build-debug
                 BUILD_TYPE=check
            - name: "build-release"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=$LOG_PATH/build-release
                 BUILD_TYPE=check
            - name: "pyodbc_test-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/pyodbc_test-cm5.3
            - name: "phoenix_quick_T4-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_quick_T4-ahw2.2
            - name: "jdbc_test-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/jdbc_test-cm5.3
            - name: "core-regress-seabase-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-seabase-ahw2.2
            - name: "core-regress-core-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-core-ahw2.2

    publishers:
      - console-log


- job:
    name: 'Check-Daily'
    node: 'master'
    project-type: multijob

    parameters:
      - string:
          name: LOG_PATH
          default: 'Daily/$BUILD_ID'

    properties:
      - github:
          url: https://github.com/apache/incubator-trafodion

    scm:
      - git:
          url: https://github.com/apache/incubator-trafodion
          wipe-workspace: false
          skip-tag: true
          branches: 
            - 'remotes/origin/master'

    triggers:
      - timed: "30 8 * * *"

    builders:
      - link-logs
      - multijob:
          name: build_test
          projects:
            - name: "build-debug"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=$LOG_PATH/build-debug
                 BUILD_TYPE=daily
            - name: "build-release"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=$LOG_PATH/build-release
                 BUILD_TYPE=daily
            - name: "core-regress-core-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-core-ahw2.2
            - name: "core-regress-seabase-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-seabase-ahw2.2
            - name: "pyodbc_test-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/pyodbc_test-ahw2.2
            - name: "core-regress-charsets-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-charsets-ahw2.2
            - name: "core-regress-qat-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-qat-ahw2.2
            - name: "core-regress-udr-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-udr-ahw2.2
            - name: "core-regress-catman1-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-catman1-ahw2.2
            - name: "core-regress-compGeneral-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-compGeneral-ahw2.2
            - name: "core-regress-executor-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-executor-ahw2.2
            - name: "core-regress-fullstack2-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-fullstack2-ahw2.2
            - name: "core-regress-hive-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-hive-ahw2.2
            - name: "phoenix_part1_T4-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_part1_T4-ahw2.2
            - name: "phoenix_part2_T4-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_part2_T4-ahw2.2
            - name: "phoenix_part1_T2-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_part1_T2-ahw2.2
            - name: "phoenix_part2_T2-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_part2_T2-ahw2.2
            - name: "jdbc_test-ahw2.2"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/jdbc_test-ahw2.2
#   Cloudera Jobs
            - name: "core-regress-core-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-core-cm5.3
            - name: "core-regress-seabase-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-seabase-cm5.3
            - name: "pyodbc_test-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/pyodbc_test-cm5.3
            - name: "core-regress-charsets-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-charsets-cm5.3
            - name: "core-regress-qat-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-qat-cm5.3
            - name: "core-regress-udr-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-udr-cm5.3
            - name: "core-regress-catman1-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-catman1-cm5.3
            - name: "core-regress-compGeneral-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-compGeneral-cm5.3
            - name: "core-regress-executor-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-executor-cm5.3
            - name: "core-regress-fullstack2-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-fullstack2-cm5.3
            - name: "core-regress-hive-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/regress-hive-cm5.3
            - name: "phoenix_part1_T4-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_part1_T4-cm5.3
            - name: "phoenix_part2_T4-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_part2_T4-cm5.3
            - name: "phoenix_part1_T2-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_part1_T2-cm5.3
            - name: "phoenix_part2_T2-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_part2_T2-cm5.3
            - name: "jdbc_test-cm5.3"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/jdbc_test-cm5.3

    publishers:
      - console-log
      - postbuildscript:
          script-only-if-succeeded: false
          script-only-if-failed: false
          builders:
            - shell: "/usr/local/bin/job-summary.sh"
      - email-ext:
          recipients: dev@trafodion.incubator.apache.org
          reply-to: no-reply@trafodion.org
          content-type: "text"
          subject: Trafodion Daily Test Result - $BUILD_ID
          save-output: true
          always: true
          failure: false
          body: |
            Daily Automated Testing

            Jenkins Job:   $BUILD_URL
            Archived Logs: http://logs.trafodion.org/$LOG_PATH
            
            Changes since previous daily build:
            ${CHANGES}
            
            Test Job Results:
            
            ${FILE,path="build_result.txt"}
