# use for single-repo workspace
- builder:
    name: gerrit-git-prep
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/gerrit-git-prep.sh https://review.trafodion.org http://zuul.trafodion.org https://review.trafodion.org/p"

# use for multiple-repo workspace
- builder:
    name: multi-git-prep
    builders:
      - shell: "/usr/local/bin/git-prep-multi-repo.sh {repos} > Git-Prep.log 2>&1"

- builder:
    name: maven-package
    builders:
      - shell: |
          savedDir=`pwd`
          cd {buildDir}
          export JAVA_HOME="/usr/lib/jvm/java-1.7.0-openjdk.x86_64"
          mvn -B clean site package install
          rc=$?
          cd $savedDir
          exit $rc

- builder:
    name: kill-traf
    builders:
      - shell: "/usr/local/bin/kill-rogue-instance.sh"

- builder:
    name: make-traf
    builders:
      - shell: "/usr/local/bin/build-traf.sh {flavor}"

- builder:
    name: pkg-traf
    builders:
      - shell: "/usr/local/bin/build-traf.sh {flavor} package"
      - shell: "/usr/local/bin/stage-traf.sh"

- builder:
    name: sql-regress
    builders:
      - shell: "/usr/local/bin/run-traf-regress.sh {dir} {suites}"

- builder:
    name: run-phoenix_test
    builders:
      - shell: '/usr/local/bin/run-phoenix_test.sh {trafCoreDir} {dcsDir} /usr/lib/jvm/java-1.7.0-openjdk.x86_64 {testDir} "{tests1}{tests2}{tests3}{tests4}"'

- builder:
    name: run-pyodbc_test
    builders:
      - shell: '/usr/local/bin/run-pyodbc_test.sh {trafCoreDir} {dcsDir} {testDir} "{tests1}"'


- builder:
    name: assert-no-binary-files
    builders:
      - shell: "/usr/local/bin/binary-file-check.sh"

- builder:
    name: puppet-lint
    builders:
      - shell: |
          if [ -f Modulefile ]; then
            MODULE=$(awk '/^name/ {print $NF}' Modulefile |tr -d \"\')
            if [ -z "$MODULE" ]; then
              echo "Module name not defined in Modulefile"
            else
              mkdir -p "$MODULE"
              rsync -a --exclude="$MODULE" --exclude ".*" . "$MODULE"
              cd "$MODULE"
            fi
          fi
          rake lint 2>&1

- builder:
    name: puppet-syntax
    builders:
      - shell: |
          find . -iname *.pp | xargs puppet parser validate --modulepath=`pwd`/modules
          for f in `find . -iname *.erb` ; do
            erb -x -T '-' $f | ruby -c
          done

- builder:
    name: run-tests
    builders:
      - shell: "./run-tests.sh {github-org} {project}"

- builder:
    name: assert-no-extra-files
    builders:
      - shell: |
          #!/bin/bash
          OUT=`git ls-files --other --exclude-standard --directory`
          if [ -z "$OUT" ]; then
              echo "No extra files created during test."
              exit 0
          else
              echo "The following un-ignored files were created during the test:"
              echo "$OUT"
              exit 0  # TODO: change to 1 to fail tests.
          fi

- builder:
    name: link-logs
    builders:
      - shell: |
          #!/bin/sh
          if test "$LOG_PATH" ; then
              echo "Detailed logs: http://static.trafodion.org/logs/$LOG_PATH/"
          else
              echo "Detailed logs: http://static.trafodion.org/logs/periodic/$JOB_NAME/$NODE_NAME/$BUILD_NUMBER/"
          fi


# ======================================================================

- publisher:
    name: tarball
    publishers:
      - archive:
          artifacts: 'dist/*.tar.gz'
      - scp:
          site: '{site}'
          files:
            - target: 'downloads/{project}/'
              source: 'dist/*.tar.gz'

- publisher:
    name: war
    publishers:
      - archive:
          artifacts: '{warfile}'
      - scp:
          site: '{site}'
          files:
            - target: '{target}'
              source: '{warfile}'

- publisher:
    name: git-log
    publishers:
      - scp:
          site: 'static.trafodion.org'
          files:
            - target: 'logs/$LOG_PATH'
              source: 'Git-Prep.log'
              copy-after-failure: true
          
- publisher:
    name: traf-make-log
    publishers:
      - scp:
          site: 'static.trafodion.org'
          files:
            - target: 'logs/$LOG_PATH'
              source: 'trafodion/core/Make.log'
              copy-after-failure: true
          
- publisher:
    name: traf-regress-log
    publishers:
      - scp:
          site: 'static.trafodion.org'
          files:
            - target: 'logs/$LOG_PATH'
              source: 'sql-regress-logs/**'
              copy-after-failure: true
              keep-hierarchy: true
          
- publisher:
    name: phoenix_test-log
    publishers:
      - scp:
          site: 'static.trafodion.org'
          files:
            - target: 'logs/$LOG_PATH/surefire-reports'
              source: 'trafodion/phoenix_test/target/surefire-reports/**'
              copy-after-failure: true
          
- publisher:
    name: console-log
    publishers:
      - scp:
          site: 'static.trafodion.org'
          files:
            - target: 'logs/$LOG_PATH'
              copy-console: true
              copy-after-failure: true

- publisher:
    name: console-log-periodic
    publishers:
      - scp:
          site: 'static.trafodion.org'
          files:
            - target: 'logs/periodic/$JOB_NAME/$NODE_NAME/$BUILD_NUMBER'
              copy-console: true
              copy-after-failure: true

- publisher:
    name: traf-release-tar
    publishers:
      - scp:
          site: 'static.trafodion.org'
          files:
            - target: 'downloads/trafodion'
              source: 'release/**'
              keep-hierarchy: true
      - scp:
          site: 'static.trafodion.org'
          files:
            - target: 'downloads/trafodion'
              source: 'pre-release/**'
              keep-hierarchy: true
          
