# Mechanism for developers to choose tests

- job:
    name: 'Requested-Test'
    node: 'master'
    project-type: multijob

    wrappers:
      - timestamps
      - build-user-vars

    parameters:
      - string:
          name: EMAIL
          default: $BUILD_USER_EMAIL
          description: "Comma separated destination for results (default: https://jenkins02.trafodion.org/me/configure)"
      - string:
          name: PULL_NUM
          description: "Pull Request Number"
      - string:
          name: BRANCH
          default: master
          description: "Target Branch of the the Pull Request"
      - choice:
          name: DISTRO
          choices:
            - cm5.3
            - ahw2.2
          description: "Distro: AmbariHortonWorks or ClouderaManager"
      - bool:
          name: sql
          default: false
          description: Run SQL regression?
      - string:
          name: sql_tests
          default:  "charsets executor fullstack2 qat hive compGeneral udr"
          description: "Space separated list of suites. Non-default: core seabase catman1"
      - bool:
          name: pyodbc
          default: false
          description: Run Python ODBC tests?
      - bool:
          name: jdbc
          default: false
          description: Run JDBC tests?
      - bool:
          name: phoenix
          default: false
          description: Run Phx tests?
      - choice:
          name: Phx_Driver
          choices:
            - T4
            - T2
          description: "Driver type to use for Phoenix"

    properties:
      - github:
          url: https://github.com/apache/incubator-trafodion

    scm:
      - git:
          url: https://github.com/apache/incubator-trafodion
          wipe-workspace: false
          skip-tag: true
          refspec: '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*'
          branches: 
            - 'origin/pr/${PULL_NUM}/head'
          changelog-against:
            remote: origin
            branch: "$BRANCH"

    builders:
      - inject:
          properties-content: |
            LOG_PATH=Requested/$BUILD_NUMBER
      - link-logs
      - multijob:
          name: tests
          projects:
            - name: "core-regress-ahw2.2"
              enable-condition: "'${sql}' == 'true' && '${DISTRO}' == 'ahw2.2'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/regress-${DISTRO}
                SUITES=${sql_tests}
            - name: "core-regress-cm5.3"
              enable-condition: "'${sql}' == 'true' && '${DISTRO}' == 'cm5.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                LOG_PATH=${LOG_PATH}/regress-${DISTRO}
                SUITES=${sql_tests}
            - name: "pyodbc_test-ahw2.2"
              enable-condition: "'${pyodbc}' == 'true' && '${DISTRO}' == 'ahw2.2'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/pyodbc_test-${DISTRO}
            - name: "pyodbc_test-cm5.3"
              enable-condition: "'${pyodbc}' == 'true' && '${DISTRO}' == 'cm5.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/pyodbc_test-${DISTRO}
            - name: "jdbc_test-ahw2.2"
              enable-condition: "'${jdbc}' == 'true' && '${DISTRO}' == 'ahw2.2'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/jdbc_test-${DISTRO}
            - name: "jdbc_test-cm5.3"
              enable-condition: "'${jdbc}' == 'true' && '${DISTRO}' == 'cm5.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/jdbc_test-${DISTRO}
            - name: "phoenix_test_T4-ahw2.2"
              enable-condition: "'${phoenix}' == 'true' && '${Phx_Driver}' == 'T4' && '${DISTRO}' == 'ahw2.2'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_test_${Phx_Driver}-${DISTRO}
            - name: "phoenix_test_T2-ahw2.2"
              enable-condition: "'${phoenix}' == 'true' && '${Phx_Driver}' == 'T2' && '${DISTRO}' == 'ahw2.2'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_test_${Phx_Driver}-${DISTRO}
            - name: "phoenix_test_T4-cm5.3"
              enable-condition: "'${phoenix}' == 'true' && '${Phx_Driver}' == 'T4' && '${DISTRO}' == 'cm5.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_test_${Phx_Driver}-${DISTRO}
            - name: "phoenix_test_T2-cm5.3"
              enable-condition: "'${phoenix}' == 'true' && '${Phx_Driver}' == 'T2' && '${DISTRO}' == 'cm5.3'"
              current-parameters: true
              kill-phase-on: NEVER
              predefined-parameters: |
                 LOG_PATH=${LOG_PATH}/phoenix_test_${Phx_Driver}-${DISTRO}

    publishers:
      - console-log
      - postbuildscript:
          script-only-if-succeeded: false
          script-only-if-failed: false
          builders:
            - shell: "/usr/local/bin/job-summary.sh"
      - email-ext:
          recipients: $EMAIL
          reply-to: no-reply@trafodion.org
          content-type: "text"
          subject: Trafodion Test Result - PR$PULL_NUM - $BUILD_ID
          save-output: true
          always: true
          body: |
            Requested Automated Testing

            Jenkins Job:   $BUILD_URL
            Archived Logs: http://traf-logs.esgyn.com/$LOG_PATH
            
            Test Job Results:
            
            ${FILE,path="build_result.txt"}

# run multiple suites on single slave
# this reduces overhead of installing, etc
# and also reduces machines consumed by manual test requests
- job-group:
    name: 'core-regress-req'

    jobs:
      - core-regress-{dist}

- job-template:
    name: 'core-regress-{dist}'
    node: 'redhat_{dist}'

    wrappers:
      - timeout:
          timeout: 600
          fail: true
      - timestamps

    parameters:
      - string:
          name: SUITES
          description: "Space separated list of test suites"

    builders:
      - link-logs
      - check-node
      - kill-traf
      - clean-testspace
      - get-build:
           flavor: "release"
      - sql-regress:
           dir: "./trafodion/core"
           suites: "$SUITES"

    publishers:
      - post-check-node
      - console-log
      - traf-regress-log
      - copy-system-logs
      - traf-runtime-log

