- job-group:
    name: 'traf-regress-sets'
    jobs:
      - traf-regress-{set}:
         set: 'A'
         suites: "charsets executor qat core"
      - traf-regress-{set}:
         set: 'B'
         suites: "compGeneral seabase hive"

- job-template:
    name: 'traf-regress-{set}'
    node: redhat

    wrappers:
      - timeout:
          timeout: 240
          fail: true
      - timestamps

    builders:
      - kill-traf
      - multi-git-prep:
           repos: "trafodion/core"
      - make-traf:
           flavor: "debug"
      - sql-regress:
           dir: "./trafodion/core"
           suites: "{suites}"
      - link-logs

    publishers:
      - console-log
      - git-log
      - traf-make-log
      - traf-regress-log

- job:
    name: 'traf-regress-experimental'
    node: redhat

    wrappers:
      - timeout:
          timeout: 240
          fail: true
      - timestamps

    builders:
      - kill-traf
      - multi-git-prep:
           repos: "trafodion/core"
      - make-traf:
           flavor: "debug"
      - sql-regress:
           dir: "./trafodion/core"
           suites: "NONE"
      - link-logs

    publishers:
      - console-log
      - git-log
      - traf-make-log
      - traf-regress-log

- job:
    name: 'traf-pub'
    node: redhat

    builders:
      - multi-git-prep:
           repos: "trafodion/core"
      - pkg-traf:
           flavor: "release"
      - link-logs

    publishers:
      - console-log
      - git-log
      - traf-make-log
      - traf-release-tar

- job:
    name: 'dcs-build'
    node: redhat

    builders:
      - gerrit-git-prep
      - maven-package:
           buildDir: "."
      - link-logs

    publishers:
      - console-log

# For phoenix_test* jobs parameters tests1-4 should contain a list of tests seperated by a comma and NO space. For instance : ExtendedQueryExecTest,ProductMetricsTest
# If parameters tests1-4 are all "" then all tests will be run
# If parameter tests1 = DONT_RUN_TESTS then none of the phoenix tests will run.  This should only be used in phoenix_test-experimental if phoenix_test is running all tests.
- job:
    name: 'phoenix_test-experimental'
    node: redhat

    wrappers:
      - timeout:
          timeout: 240
          fail: true
      - timestamps

    builders:
      - kill-traf
      - multi-git-prep:
           repos: "trafodion/core trafodion/dcs trafodion/phoenix_test"
      - make-traf:
           flavor: "debug"
      - maven-package:
           buildDir: "trafodion/dcs"
      - kill-traf
      - run-phoenix_test:
           trafCoreDir: "trafodion/core"
           dcsDir: "trafodion/dcs"
           testDir: "trafodion/phoenix_test"
           tests1: "DONT_RUN_TESTS"
           tests2: ""
           tests3: ""
           tests4: ""
      - link-logs

    publishers:
      - junit:
           results: "trafodion/phoenix_test/target/surefire-reports/*.xml"
      - console-log
      - traf-make-log
      - git-log
      - phoenix_test-log

- job:
    name: 'phoenix_test'
    node: redhat

    wrappers:
      - timeout:
          timeout: 240
          fail: true
      - timestamps

    builders:
      - kill-traf
      - multi-git-prep:
           repos: "trafodion/core trafodion/dcs trafodion/phoenix_test"
      - make-traf:
           flavor: "debug"
      - maven-package:
           buildDir: "trafodion/dcs"
      - kill-traf
      - run-phoenix_test:
           trafCoreDir: "trafodion/core"
           dcsDir: "trafodion/dcs"
           testDir: "trafodion/phoenix_test"
           tests1: ""
           tests2: ""
           tests3: ""
           tests4: ""
      - link-logs

    publishers:
      - junit:
           results: "trafodion/phoenix_test/target/surefire-reports/*.xml"
      - console-log
      - git-log
      - phoenix_test-log

# For pyodbc_test* jobs parameter tests1 should contain a list of tests seperated by a space. For instance : test_p2.ConnectTest.test11 test_p2.ConnectTest.test12
# If parameter tests1 is "" then all tests will be run
# If parameter tests1 = DONT_RUN_TESTS then none of the pyodbc tests will run.  This should only be used in pyodbc_test-experimental if pyodbc_test is running all tests.
- job:
    name: 'pyodbc_test-experimental'
    node: redhat

    wrappers:
      - timeout:
          timeout: 30
          fail: true
      - timestamps

    builders:
      - kill-traf
      - multi-git-prep:
           repos: "trafodion/core trafodion/dcs"
      - make-traf:
           flavor: "debug"
      - maven-package:
           buildDir: "trafodion/dcs"
      - kill-traf
      - run-pyodbc_test:
           trafCoreDir: "trafodion/core"
           dcsDir: "trafodion/dcs"
           testDir: "trafodion/dcs/src/test/pytests"
           tests1: "DONT_RUN_TESTS"
      - link-logs

    publishers:
      - junit:
           results: "trafodion/dcs/src/test/pytests/logs/test_report.xml"
      - console-log
      - git-log
      - pyodbc_test-log

- job:
    name: 'pyodbc_test'
    node: redhat

    wrappers:
      - timeout:
          timeout: 30
          fail: true
      - timestamps

    builders:
      - kill-traf
      - multi-git-prep:
           repos: "trafodion/core trafodion/dcs"
      - make-traf:
           flavor: "debug"
      - maven-package:
           buildDir: "trafodion/dcs"
      - kill-traf
      - run-pyodbc_test:
           trafCoreDir: "trafodion/core"
           dcsDir: "trafodion/dcs"
           testDir: "trafodion/dcs/src/test/pytests"
           tests1: ""
      - link-logs

    publishers:
      - junit:
           results: "trafodion/dcs/src/test/pytests/logs/test_report.xml"
      - console-log
      - git-log
      - pyodbc_test-log


# Simple file type check can run on master
# Does not need to be exclusive
- job-template:
    name: 'gate-{name}-check-for-binary'
    node: master

    builders:
      - gerrit-git-prep
      - assert-no-binary-files
      - link-logs

    publishers:
      - console-log
