- job-template:
    name: 'gate-{name}-chef-unit'
    node: '{node}'

    builders:
      - gerrit-git-prep
      - chef-cookbook-prep
      - chef-cookbook-rspec

    publishers:
      - console-log

- job-template:
    name: 'gate-{name}-chef-lint'
    node: '{node}'

    builders:
      - gerrit-git-prep
      - chef-cookbook-prep
      - chef-cookbook-lint

    publishers:
      - console-log

- job-template:
    name: 'gate-{name}-chef-style'
    node: '{node}'

    builders:
      - gerrit-git-prep
      - chef-cookbook-prep
      - chef-cookbook-style

    publishers:
      - console-log

- job:
    name: gate-openstack-chef-repo
    node: precise

    builders:
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          mkdir -p .cookbooks .bundle
          ruby1.9.1 /usr/bin/bundle install --path=.bundle
          # Validates cookbooks
          ruby1.9.1 /usr/bin/bundle exec berks install --path=.cookbooks
          # Validates roles
          ruby1.9.1 /usr/bin/bundle exec spiceweasel infrastructure.yml --debug

    publishers:
      - console-log
