- job:
    name: gate-gitdm
    node: precise

    builders:
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          export TEMPDIR=${TEMPDIR:-$(mktemp -d $(pwd)/dmtmp-XXXXXX)}
          export GITBASE=${TEMPDIR}/git
          export LP_STATS=n
          bash ./do-it.sh
      - link-logs

    publishers:
      - console-log


- job:
    name: periodic-gitdm
    node: precise

    builders:
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          export TEMPDIR=${TEMPDIR:-$(mktemp -d $(pwd)/dmtmp-XXXXXX)}
          export GITBASE=${TEMPDIR}/git
          export LP_STATS=n
          bash ./do-it.sh
      - link-logs

    publishers:
      - console-log-periodic
