- job:
    name: gate-horizon-selenium
    node: precise

    builders:
      - gerrit-git-prep
      - selenium:
          github-org: openstack
          project: horizon

    publishers:
      - console-log

- job:
    name: gate-horizon-python27-django14
    node: precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    builders:
      - gerrit-git-prep
      - shell: '/usr/local/jenkins/slave_scripts/run-unittests.sh 27dj14 openstack horizon'
      - assert-no-extra-files

    publishers:
      - test-results
      - console-log
