- job-template:
    name: '{name}-docs'
    node: precise

    builders:
      - gerrit-git-prep
      - docs:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - ftp:
          site: '{doc-publisher-site}'
          source: 'doc/build/html/**'
          target: 'developer/{name}'
          remove-prefix: 'doc/build/html'
          excludes: ''
      - console-log


- job-template:
    name: '{name}-merge-release-tags'
    concurrent: false

    builders:
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          TAG=`echo $ZUUL_REFNAME | sed 's/refs.tags.//'`
          /usr/local/jenkins/slave_scripts/merge_tags.sh $TAG

    publishers:
      - console-log

    node: 'proposal'


- job-group:
    name: openstack-publish-jobs
    jobs:
      - '{name}-docs'
      - '{name}-merge-release-tags'
