- job-template:
    name: '{name}-pypi-upload'
    node: pypi

    builders:
      - gerrit-git-prep
      - shell: |
          /usr/local/jenkins/slave_scripts/pypi-upload.sh {name} {tarball-site}

    publishers:
      - console-log


- job-group:
    name: pypi-jobs
    jobs:
      - '{name}-pypi-upload'
