- job:
    name: gate-solum-devstack-dsvm
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export ENABLED_SERVICES=solum
          export PROJECTS="stackforge/solum"

          function pre_test_hook {
              # Install solum devstack integration
              SOLUM_BASE=/opt/stack/new/solum/contrib/devstack
              DEVSTACK_BASE=/opt/stack/new/devstack
              cp $SOLUM_BASE/lib/* $DEVSTACK_BASE/lib
              cp $SOLUM_BASE/extras.d/* $DEVSTACK_BASE/extras.d
          }
          export -f pre_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log
